# Generated by Django 4.2.3 on 2023-08-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('Trainer_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Trainer_subject', models.CharField(max_length=100)),
                ('Trainer_age', models.IntegerField()),
            ],
        ),
    ]
